chore: verify bootstrap version format before merge
It is important that the bootstrap version is pointing to a published
tag, so that merged changes do not end up pointing to an ephemeral ref
on the shared-sites repository. This change splits the bootstrap version
into a separate file resources/.bootstrap-required-version, so that this
version string can be easily checked in ci.yml, preventing merge of pull
requests that point to branch names instead of tag names. For simplicity,
the test verifies the shape of the version string as 'v#.#.#', but does
not verify that it actually points to a tag, so in theory it could be
fooled, but in practice we never use that pattern for branch names.

Test-bot: skip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,3 +82,18 @@ jobs:
         source ./_common/tests.inc.sh
         set -e
         do_test_print_container_error_logs "$CONTAINER_DESC"
+
+    - name: Verify .bootstrap-required-version
+      if: ${{ !cancelled() }}
+      shell: bash
+      run: |
+        # We want to avoid merging a bootstrap version that is not based on a published tag
+        # in the shared-sites repo. We will do this with a heuristic based on the normal
+        # shape of the tags, which is `v#.#.#`. Any other shape we will assume is a test
+        # branch.
+        cat resources/.bootstrap-required-version | grep -qP '^v\d+\.\d+\.\d+$' || (
+          echo "This branch cannot be merged, because resources/.bootstrap-required-version "
+          echo "references '$(cat resources/.bootstrap-required-version)', which does not"
+          echo "appear to be a published tag -- is it a test branch?"
+          exit 1
+        )
